Update copyright header in license
eclipse-ee4j/jstl-api pull request #121
Opened 2020-08-31 17:43 UTC by pnicolucci

fixes #120

2020-08-31 19:37 UTC, arjantijms requested changes

2020-08-31 19:37 UTC, arjantijms commented on spec/src/main/asciidoc/license-efsl.adoc
> +== Copyright (c) 2018, 2020 Eclipse Foundation.
I think it should just add a header:

```
== Copyright

Copyright (C) 2018, 2020 Eclipse Foundation. 
```

2020-08-31 19:56 UTC, pnicolucci commented on spec/src/main/asciidoc/license-efsl.adoc
> +== Copyright (c) 2018, 2020 Eclipse Foundation.
doh, good catch! Fixed.

2020-09-04 08:30 UTC, arjantijms approved these changes

2020-09-04 08:30 UTC, merged